# Generated by Django 5.1.3 on 2024-11-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jabaa_admin_dashboard', '0002_account_date_joined_account_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
    ]
